### ISSUE TITLE
Hybridness of Chromosomes

### ISSUE THREAD

**Issue by MoritzBauer** [biocorecrg/allele_specific_RNAseq#3]
The following graphs show the hybridness of each chromosome

![Hybrid_1](https://user-images.githubusercontent.com/39186738/76211180-eb48d980-6205-11ea-962c-76e8b92653a8.png)
![Hybrid_2](https://user-images.githubusercontent.com/39186738/76211188-ee43ca00-6205-11ea-80d1-e0a20618a55a.png)

**Comment by lucacozzuto** [comment]
Hi, do you want to add this plot as an extra step? Do you want to send me the code?

**Comment by MoritzBauer** [comment]
I haven't done this myself, this was work from Quique, so finding the code would be a bit tough. But I anyway feel we do not need to add this, since this goes beyond of what the pipeline is there to do.

**Comment by lucacozzuto** [comment]
Good. So I close this issue too! I hope you are fine!
