### ISSUE TITLE
module makeAnno 

### ISSUE THREAD

**Issue by llonchsilvia** [biocorecrg/allele_specific_RNAseq#31]
Hi Luca, 
I am having issues with the module makeAnno... 
I am trying to run this command: 
`cd makeAnno`

`nextflow run make_anno.nf -bg --vcffile mgp.v5.merged.snps_all.dbSNP142.vcf.gz --speciesA CAST_EiJ --speciesB 129S1_SvImJ --genome GRCm38_68.fa --outvcf CAST_EiJ-129S1_SvImJ.vcf > log
`

and I get absolutely no result.. I've been reading the issue Mortiz opened about the $baseDir change, and tried everything is there... I changed the path to the vcf files and the reference genome, put them in different folders in the cluster and tested... but I can't get it to work... 

What else would you suggest to try?  

Thanks!

**Comment by lucacozzuto** [comment]
So, makeAnno creates an output folder named **filteredVCF** and generates there the gzipped output. I'll update the README.md
