### ISSUE TITLE
make_anno with data from reference genome strain cross

### ISSUE THREAD

**Issue by Ni-Ar** [biocorecrg/allele_specific_RNAseq#34]
Hi @lucacozzuto ,

I have a doubt about how to use the `make_anno.nf` script in a case in which the RNA-seq comes from a mouse samples that is the cross between C57BL/6J and CAST/EiJ.

The thing is that the mouse genome that one can get from `ftp-mouse.sanger.ac.uk/ref/GRCm38_68.fa` is from the strain C57BL/6J (as stated in the `readme` of the [mouse genomes project](https://www.sanger.ac.uk/sanger/Mouse_SnpViewer/rel-1505)). 

So, I believe, in the vcf header of `mgp.v5.merged.snps_all.dbSNP142.vcf` there's no `C57BL_6J`, while there are `129S1_SvImJ` and `CAST_EiJ` for example. 

With this type of data what should be specified in `--speciesB ` in the following run:

```
nextflow run make_anno.nf -with-singularity -bg --vcffile mgp.v5.merged.snps_all.dbSNP142.vcf.gz \
                                             --speciesA CAST_EiJ \
                                             --speciesB XXX \
                                             --genome GRCm38_68.fa --outvcf CAST_EiJ-C57BL_6J.vcf > log
```

Thanks,
Nicco

**Comment by lucacozzuto** [comment]
Hi,
We could think about a special case. Something like --speciesB "reference" so it will just keep the original base (REF) in that position.
But it has to be developed. Let me know if you would need it  

Luca

**Comment by Ni-Ar** [comment]
Let me try to see if I got this right: 

If I understand correctly in the case of `129S1_SvImJ` and `CAST_EiJ` any SNP coming from those 2 strains is masked and the new genome gets an `N` base in that position. 

In your `--speciesB "reference"` suggestion the masking would occur only at position where the `--speciesA` SNPs are present, right?

**Comment by lucacozzuto** [comment]
Yes.

**Comment by Ni-Ar** [comment]
Okay, we'll discuss this possibility and get back to you.
