### ISSUE TITLE
Mapping error

### ISSUE THREAD

**Issue by mercedes-barrero** [biocorecrg/allele_specific_RNAseq#36]
Hi Luca,

The pipeline was working until it got to the mapping step. Then I got this error:

Error executing process > 'mapping ()'

Caused by:
  **File `/ReadsPerGene.out.tab` is out of the scope of process working dir:** /nfs/users/bpayer/mbarrero/allele_specific_RNAseq/work/96/64248a8b984465abda0413c3fb2bf7

Source block:
  def output = "${pair_id}"
  def variants = unzipBash("${variants_file}")
  """
          if [ `echo "${reads}"| cut -f 1 -d " " | grep ".gz"` ]; then gzipped=" --readFilesCommand zcat "; else gzipped=""; fi
              STAR --genomeDir ${STARgenome} \
                   --readFilesIn ${reads} \
                    \$gzipped \
                    --waspOutputMode SAMtag \
                    --outSAMunmapped Within \
                    --outSAMtype BAM SortedByCoordinate \
                    --runThreadN ${task.cpus} \
                    --outFileNamePrefix ${pair_id} \
                    --quantMode GeneCounts \
                    --outSAMattributes NH HI AS nM NM MD jM jI XS MC ch vA vW vG \
                    --varVCFfile ${variants};
                    mkdir ${output}
                    mv *.out.tab ${output}/
                    mv *Aligned* ${output}/
                    mv *Log* ${output}/
   
          	samtools index ${pair_id}/*.out.bam
          """

Work dir:
  /nfs/users/bpayer/mbarrero/allele_specific_RNAseq/work/96/64248a8b984465abda0413c3fb2bf7

**Comment by lucacozzuto** [comment]
Hi, I think the problem is in the definition of the reads... 

reads                         : /users/bpayer/mbarrero/allele_specific_RNAseq/test/{NPC1_14191AAC_CGA
TGT_R1_001,NPC1_14191AAC_CGATGT_R2_001}.fastq.g

it should be something like

reads                         : /users/bpayer/mbarrero/allele_specific_RNAseq/test/*.fastq.gz

since the program uses the part indicated by the asterisk as ID. Maybe this should be explained better in the README...

**Comment by lucacozzuto** [comment]
wait, sorry I did not see that is paired end... So for paired end you need another syntax for specifying the pairs:

```
/users/bpayer/mbarrero/allele_specific_RNAseq/test/*_R{1,2}_001.fastq.gz
```
I'll add this to the README too.
