### ISSUE TITLE
High percentage of duplicated reads

### ISSUE THREAD

**Issue by mercedes-barrero** [biocorecrg/allele_specific_RNAseq#37]
Hi Luca,

I have run the pipeline for all my samples and it worked, but in the multiQC report I observe a high percentage of duplicate reads for all the samples. Do you think this is a problem? Can it affect the further analysis?
<img width="1445" alt="Screenshot 2022-01-14 at 11 57 50" src="https://user-images.githubusercontent.com/63344685/149504869-d38a1e5e-1fcf-4b3a-8b79-5f8551aa771f.png">

Thanks!

**Comment by lucacozzuto** [comment]
Hi, it depends on the expression of the most abundant transcripts.

**Comment by Ni-Ar** [comment]
If that's mRNA-seq it's pretty okay to have duplicated reads.

**Comment by lucacozzuto** [comment]
Yes, I think it is rather ok

**Comment by mercedes-barrero** [comment]
OK thanks!
