### ISSUE TITLE
strandness

### ISSUE THREAD

**Issue by mercedes-barrero** [biocorecrg/allele_specific_RNAseq#38]
Hi Luca,

I have a quick question. In my stranded total RNAseq, if I have paired-end sequencing, what to I have to specify in "strandness" in the params.config? Is it "reverse"?

Thanks a lot,
Mercedes

**Comment by lucacozzuto** [comment]
Dear @mercedes-barrero, this depends on the sequencing protocol used.

**Comment by lucacozzuto** [comment]
A possible way to guess the protocol is by looking at the report produced by multiQC. The STAR -> Gene Counts
 section shows the results for forward, reverse, and unstranded. If you see that forward has a number of reads overlapping genes greater than reverse: it is likely forward. The opposite for reverse. If they are similar and unstranded is higher, it is likely unstranded.
