### ISSUE TITLE
Error executing process > 'getReadLength'

### ISSUE THREAD

**Issue by tmattimoe** [biocorecrg/allele_specific_RNAseq#43]
Hi Luca,

I am trying to run the allele-specific pipeline for the first time and i got this error as soon as it started. Any ideas what is going wrong?

Thanks,
Tom

Workflow execution completed unsuccessfully
The exit status of the task that caused the workflow execution to fail was: 255

Error executing process > 'getReadLength'

Caused by:
  Process `getReadLength` terminated with an error exit status (255)

Command executed:

  if [ `echo K0EP02_15186AAD_GCCGTGAAGT-GCATGGAGCG_R1_001.fastq.gz | grep "gz"` ]; then cat="zcat"; else cat="cat"; fi
  $cat K0EP02_15186AAD_GCCGTGAAGT-GCATGGAGCG_R1_001.fastq.gz | awk '{num++}{if (num%4==2){line++; sum+=length($0)} if (line==100) {printf "%.0f", sum/100; exit} }'

Command exit status:
  255

Command output:
  (empty)

Command error:
  [91mERROR  : Unknown image format/type: /nfs/users/bpayer/tmattimoe/allele_specific/allele_specific_RNAseq/singularity/biocorecrg-asrnaseq-0.3.img
  [0m[31mABORT  : Retval = 255
  [0m

Work dir:
  /nfs/users/bpayer/tmattimoe/allele_specific/allele_specific_RNAseq/work/d4/96570abc650b44ada60f0dc9c50993

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

**Comment by lucacozzuto** [comment]
Hi, you have likely a problem of versions of singularity. Are you using a cluster?
